services:
  - type: web
    name: companies-house-change-monitor
    env: docker
    region: frankfurt
    plan: starter
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REST_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FILING_SSE_URL
        value: https://stream.companieshouse.gov.uk/filings
      - key: PSC_SSE_URL
        value: https://stream.companieshouse.gov.uk/persons-with-significant-control
      - key: PSC_STATEMENTS_SSE_URL
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
  - type: worker
    name: companies-house-change-worker
    env: docker
    region: frankfurt
    plan: starter
    dockerContext: .
    dockerfilePath: ./Dockerfile
    dockerCommand: python stream_worker.py
    envVars:
      - key: STREAM_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FILING_SSE_URL
        value: https://stream.companieshouse.gov.uk/filings
      - key: PSC_SSE_URL
        value: https://stream.companieshouse.gov.uk/persons-with-significant-control
      - key: PSC_STATEMENTS_SSE_URL
        sync: false
